spring.application.name=sequelas-backend
server.port=${PORT:8080}

# Conexão via variáveis separadas (mais seguro)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?ssl=true&sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# Dialeto (forçado)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=false
